process.env.VERCEL_FUNCTION = '1';

// The server bundle is generated by `npm run build` before Vercel packages this function.
// @ts-ignore Generated ESM bundle is created by the build command.
import handler from '../dist/server.mjs';

export default handler;
