process.env.VERCEL_FUNCTION = '1';

// The server bundle is generated by `npm run build` before Vercel packages this function.
// @ts-ignore Generated ESM bundle is created by the build command.
import handler from '../dist/server.mjs';
import { getServiceClient, serviceClientConfigError } from '../server/db/supabase';

const publicProjects = async (_req: any, res: any) => {
  try {
    const db = getServiceClient();
    if (!db) return res.status(503).json({ error: serviceClientConfigError() });

    const { data: projects, error } = await db
      .from('projects')
      .select('id, title, description, department, status, visibility, trl, research_area, image_url, budget, start_date, owner_id, created_at, funding_amount_usd, open_to_collaboration, technical_details_url, achievements, needs, views, expressions_of_interest, requests, disclosure_status')
      .eq('visibility', 'Public')
      .in('disclosure_status', ['Approved', 'Published'])
      .order('created_at', { ascending: false });
    if (error) throw error;

    const ownerIds = Array.from(new Set((projects || []).map((project: any) => project.owner_id).filter(Boolean)));
    const profileMap = new Map<string, any>();
    if (ownerIds.length > 0) {
      const { data: profiles, error: profileError } = await db
        .from('profiles')
        .select('id, name, email, avatar_url, department, company')
        .in('id', ownerIds);
      if (profileError) throw profileError;
      for (const profile of profiles || []) profileMap.set(profile.id, profile);
    }

    return res.json({
      projects: (projects || []).map((project: any) => {
        const profile = profileMap.get(project.owner_id);
        return {
          ...project,
          owner_name: profile?.name || 'University Researcher',
          owner_email: profile?.email || '',
          owner_avatar: profile?.avatar_url || '',
          owner_department: profile?.department || project.department || '',
          owner_company: profile?.company || '',
        };
      }),
    });
  } catch (error) {
    console.error('Public projects load error:', error);
    return res.status(500).json({ error: 'Projects could not be loaded.' });
  }
};

const vercelHandler = async (req: any, res: any) => {
  const path = (req.url || '').split('?')[0];
  if (path === '/api/projects' || path === '/api/public-projects') {
    return publicProjects(req, res);
  }
  return handler(req, res);
};

export default vercelHandler;
